### ISSUE TITLE
Stake login issue on 4.2.5.1. Same on 4.2.5.0.

### ISSUE THREAD

**Issue by gngenius02** [GamblingWonder/Dicebot#13]
After clicking on the login button i get an error:

`System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies. The specified module could not be found.`

I have verified the above file is in the DiceBot folder. I can click continue through that error and the window that's supposed to load the page pops up but the browser never gets loaded. If I click on Continue at that point I get a new error:

`System.Exception: IBrowserHost instance is null. Browser has likely not finished initializing or is in the process of disposing.`

Clicking continue on the second error box yields no change. I am attaching the full error details from both errors below.  

[CefSharp ERROR.txt](https://github.com/GamblingWonder/Dicebot/files/9761033/CefSharp.ERROR.txt)
[IBrowserHost ERROR.txt](https://github.com/GamblingWonder/Dicebot/files/9761099/IBrowserHost.ERROR.txt)

NOTE: This issue is only caused on a vps. I can't recreate the second issue on my local machine or my local vms. First error popped out on first run and then never again.  I ran all windows updates to see if that would help. It did not. Not sure what else to try.

**Comment by WinMachine777** [comment]
Hello!

In some VM's you need to install the Visual C++ Redistributable  x86,
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist



Nino ***@***.***> escreveu no dia quarta, 12/10/2022 à(s)
04:05:

**Comment by gngenius02** [comment]
Hello, 

After installing Visual C++ Redistributable, and updating to DiceBot v4.2.5.5, I am able login. Thanks for your help!

> Hello! In some VM's you need to install the Visual C++ Redistributable x86, https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
