### ISSUE TITLE
Release 4.2.6.6. - SETTINGS.dcb - folder instead of file created

### ISSUE THREAD

**Issue by TristanIvanov** [GamblingWonder/Dicebot#17]
I started the release 4.2.6.6, logged in, but could not start the script in prog. mode. 
In the console the was written something like: LUA error, no write permission to SETTINGS.dcb.
In the directory I've found a folder with the name SETTINGS.dcb. 
I deleted it and created a new text file with the same name, so it worked perfectly.
(Not tested in other Releases)

**Comment by WinMachine777** [comment]
Hello!
Thanks for your feedback.

This issue is already fixed in latest version.

Best regards
