### ISSUE TITLE
Error when start 4.2.9.6 and 4.2.9.7 versions

### ISSUE THREAD

**Issue by ValoWaking** [GamblingWonder/Dicebot#22]
Hi, i have an error when start 4.2.9.6 and 4.2.9.7 versions

![awd](https://user-images.githubusercontent.com/37003886/222328342-29bbc332-44f3-421f-b631-df4f83be9bbb.jpg)

**Comment by ValoWaking** [comment]
OS is Windows 7 x64
Now i tried:
Update Visual C++
Update Net. Framework 

but this is not helped for me

What version of Visual C++ you used to compile this versions?

**Comment by ValoWaking** [comment]
Why u deliting all works version? OMG

**Comment by ValoWaking** [comment]
I'm reinstal net framework 4.8 and install KB4515847 for framework 4.8 and error is gone for me on latest verison 4.2.9.72

**Comment by WinMachine777** [comment]
hello!
the latest version fix the issues with cefsharp.

ValoWaking ***@***.***> escreveu no dia sexta, 3/03/2023 à(s)
00:52:
