### ISSUE TITLE
MinBet Feature?

### ISSUE THREAD

**Issue by gngenius02** [GamblingWonder/Dicebot#5]
Can we add a minBet variable, for DuckDice, in programmer mode? It would be really nice to select a minBet automatically, vs needing to check minbet each time. Since the site's minbet of each currency is tied to the price of BTC the minbet is constantly changing. I am not sure how to go about adding this myself, I would be glad to do the work and submit a PR with a little guidance.

The data can be found in the public api using the following:

Currency = "USDT"

https://duckdice.io/api/common/{Currency}

data.currency.minBet

**Comment by WinMachine777** [comment]
Hello!
What are the main benefits of have that on a variable?
Why not just have the minBet validation on native side, if there was any way to get that value from the casino website?

Best regards!

**Comment by gngenius02** [comment]
Im not sure how you mean. Do you mean to get the value from the casino website using lua? How would that approach go? 

It would be nice to have the info automatically pulled on start of script, which I think would mean adding it to the C# code. Then accessing the data from the lua script, via a minBet variable.
