### ISSUE TITLE
Dicebot 4.2.2.0 issue

### ISSUE THREAD

**Issue by needsolo** [GamblingWonder/Dicebot#7]
there is some issue when we minimise the dicebot

![image](https://user-images.githubusercontent.com/30566931/193738111-639a3dad-e4df-4ea4-adcf-4fec1e05ca71.png)
![Region](https://user-images.githubusercontent.com/30566931/193738234-1b93951f-70f4-4dc2-9a5f-e232585f0d2f.jpg)

**Comment by WinMachine777** [comment]
Hello!
This issue was happening on v4.2.1.0. Its fixed on latest version 4.2.2.0

**Comment by vsdadm01** [comment]
til not working.
![image](https://user-images.githubusercontent.com/91514113/193771725-9dc5769b-c7a3-4bbc-8d88-3d133bf5f397.png)

**Comment by WinMachine777** [comment]
> til not working. ![image](https://user-images.githubusercontent.com/91514113/193771725-9dc5769b-c7a3-4bbc-8d88-3d133bf5f397.png)

Hello!
This isnt the same issue.

**Comment by needsolo** [comment]
Respected Winmachine777 :- when i click on Dicebot 4.2.2.0 it download old version, due to this the problem is still there as it download old version with same minimise error
